name: globalmapper
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.10
  - pip=21.0.1
  - numpy=1.20.1
  - cudatoolkit=11.1
  - pytorch=1.8.0
  - torchvision=0.9.0
  - matplotlib=3.3.4
  - networkx=2.5
  - pickle5
  - pillow=8.2.0
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - seaborn=0.11.1
  - yaml=0.2.5
  - shapely=1.7.1
  - pip:
    - tensorboard-logger==0.1.0
    - torch-geometric==2.0.3
    - pytorch-scatter=2.0.8
    - pytorch-sparse=0.6.12
